// Maps the plain icon-name strings stored by the backend (website_content
// models store icons as e.g. "Zap", "Nfc", "BarChart3") to lucide-react
// components, for rendering previews + a picker in the Website Content admin
// forms. Not exhaustive (lucide has ~1500 icons) — covers every icon name
// actually used by the seeded content plus a reasonably useful common set.
import {
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  Calendar,
  CheckCircle2,
  Clock,
  Cloud,
  CreditCard,
  Feather,
  Gift,
  Globe,
  Heart,
  HelpCircle,
  Layers,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Nfc,
  PackageCheck,
  Phone,
  QrCode,
  RefreshCcw,
  RefreshCw,
  Rocket,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  TrendingUp,
  Trophy,
  UserCheck,
  UserCircle2,
  UserCog,
  Users,
  User,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react"

export const ICON_MAP: Record<string, LucideIcon> = {
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  Calendar,
  CheckCircle2,
  Clock,
  Cloud,
  CreditCard,
  Feather,
  Gift,
  Globe,
  Heart,
  HelpCircle,
  Layers,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Nfc,
  PackageCheck,
  Phone,
  QrCode,
  RefreshCcw,
  RefreshCw,
  Rocket,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  TrendingUp,
  Trophy,
  UserCheck,
  UserCircle2,
  UserCog,
  Users,
  User,
  Wallet,
  Wifi,
  Zap,
}

export const ICON_NAMES = Object.keys(ICON_MAP).sort()

const FALLBACK_ICON: LucideIcon = HelpCircle

/** Resolves an icon name string to its lucide-react component, falling back
 * to HelpCircle for unknown/empty names so a bad backend value never crashes
 * the admin UI. */
export function resolveIcon(name?: string | null): LucideIcon {
  if (!name) return FALLBACK_ICON
  return ICON_MAP[name] ?? FALLBACK_ICON
}
