# Generated by Django 6.0.1 on 2026-09-07 11:55

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_alternate_phone_profile_city_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_maps_url',
            field=models.URLField(blank=True, validators=[profiles.models.validate_google_maps_url]),
        ),
    ]
