# Generated by Django 6.0.1 on 2026-09-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_google_maps_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="selected_template",
            field=models.CharField(
                choices=[
                    ("classic", "classic"),
                    ("signature", "signature"),
                    ("creative", "creative"),
                    ("executive", "executive"),
                    ("luxury", "luxury"),
                    ("future", "future"),
                    ("nature", "nature"),
                    ("glass", "glass"),
                    ("impact", "impact"),
                ],
                default="classic",
                max_length=30,
            ),
        ),
    ]
