# Generated by Django 6.0.1 on 2026-09-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_selected_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="google_review_url",
            field=models.URLField(blank=True),
        ),
    ]
