# Generated by Django 6.0.1 on 2026-09-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_google_review_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='luxury_theme',
            field=models.CharField(choices=[('green', 'Luxury Green'), ('blue', 'Luxury Blue'), ('black', 'Luxury Black')], default='black', max_length=10),
        ),
    ]
