# Generated by Django 6.0.1 on 2026-09-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_luxury_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='future_theme',
            field=models.CharField(choices=[('green', 'Future Green'), ('blue', 'Future Blue'), ('black', 'Future Black')], default='green', max_length=10),
        ),
    ]
