# Generated by Django 6.0.5 on 2026-09-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_profile_luxury_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="show_contact_info",
        ),
        migrations.AddField(
            model_name="profile",
            name="show_address",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_city",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_phone",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_state",
            field=models.BooleanField(default=True),
        ),
    ]
