# Generated by Django 6.0.1 on 2026-09-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_future_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='impact_theme',
            field=models.CharField(choices=[('red', 'Impact Red'), ('blue', 'Impact Blue'), ('black', 'Impact Black'), ('white', 'Impact White')], default='red', max_length=10),
        ),
    ]
