# Generated by Django 6.0.1 on 2026-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_impact_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='glass_theme',
            field=models.CharField(choices=[('white', 'Glass White'), ('blue', 'Glass Blue'), ('green', 'Glass Green')], default='blue', max_length=10),
        ),
    ]
