# Generated by Django 6.0.5 on 2026-09-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_remove_profile_show_contact_info_and_more"),
        ("profiles", "0009_profile_glass_theme"),
    ]

    operations = []
