# Generated by Django 6.0.5 on 2026-09-07 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutBuiltFromExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True, default="Built From Experience", max_length=255
                    ),
                ),
                ("subtitle", models.TextField(blank=True, default="")),
                ("paragraph_1", models.TextField(blank=True, default="")),
                ("paragraph_2", models.TextField(blank=True, default="")),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "image_public_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "About Built From Experience",
                "verbose_name_plural": "About Built From Experience",
            },
        ),
        migrations.CreateModel(
            name="AboutFeatureHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                ("icon", models.CharField(help_text="Lucide icon name", max_length=50)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "About Story Feature Highlight",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AboutMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge",
                    models.CharField(blank=True, default="OUR MISSION", max_length=150),
                ),
                ("heading", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "About Mission",
                "verbose_name_plural": "About Mission",
            },
        ),
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_title",
                    models.CharField(default="About VR's NEXORA", max_length=200),
                ),
                ("page_subtitle", models.TextField(blank=True, default="")),
                (
                    "story_badge",
                    models.CharField(blank=True, default="OUR STORY", max_length=100),
                ),
                (
                    "story_title",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("story_paragraph_1", models.TextField(blank=True, default="")),
                ("story_paragraph_2", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Page",
                "verbose_name_plural": "About Page",
            },
        ),
        migrations.CreateModel(
            name="AboutWhyChoose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("icon", models.CharField(help_text="Lucide icon name", max_length=50)),
                (
                    "gradient",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional CSS gradient",
                        max_length=255,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "About Why Choose",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("logo_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "logo_public_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(help_text="Lucide icon name", max_length=50)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Feature",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "button_text",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "button_link",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Home CTA",
                "verbose_name_plural": "Home CTA",
            },
        ),
        migrations.CreateModel(
            name="HomeHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("badge", models.CharField(blank=True, default="", max_length=150)),
                ("heading", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "primary_cta_text",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "primary_cta_link",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "secondary_cta_text",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "secondary_cta_link",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "hero_image_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "hero_image_public_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home Hero",
                "verbose_name_plural": "Home Hero",
            },
        ),
        migrations.CreateModel(
            name="HomeHeroFeatureHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Lucide icon name, e.g. Zap", max_length=50
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Home Hero Feature Highlight",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeHowItFeels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("badge", models.CharField(blank=True, default="", max_length=150)),
                ("heading", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Home How It Feels",
                "verbose_name_plural": "Home How It Feels",
            },
        ),
        migrations.CreateModel(
            name="HomeHowItFeelsPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(help_text="Lucide icon name", max_length=50)),
                ("text", models.CharField(max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Home How It Feels Point",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HowItWorksStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField(default=1)),
                ("icon", models.CharField(help_text="Lucide icon name", max_length=50)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "How It Works Step",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[("home", "Home"), ("about", "About")],
                        default="home",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(help_text="e.g. 10K+, 99.9%", max_length=50),
                ),
                (
                    "label",
                    models.CharField(help_text="e.g. Happy Customers", max_length=150),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional Lucide icon name",
                        max_length=50,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Statistic",
                "verbose_name_plural": "Statistics",
                "ordering": ["page", "display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "designation",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("company", models.CharField(blank=True, default="", max_length=150)),
                ("review", models.TextField()),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "image_public_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(help_text="Lucide icon name", max_length=50)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Value",
                "ordering": ["display_order", "id"],
            },
        ),
    ]
