# Generated by Django 6.0.1 on 2026-09-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_content", "0002_contactmessagereply"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "site_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("site_phone", models.CharField(blank=True, default="", max_length=30)),
                (
                    "site_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("INR", "INR - Indian Rupee"),
                            ("USD", "USD - US Dollar"),
                            ("EUR", "EUR - Euro"),
                        ],
                        default="INR",
                        max_length=10,
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "General Settings",
                "verbose_name_plural": "General Settings",
            },
        ),
    ]
