# Generated by Django 6.0.1 on 2026-09-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0004_seed_general_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBottomBarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='', help_text='Lucide icon name. Leave blank for the first item to show the customer avatar stack instead.', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Bottom Bar Item',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RenameField(
            model_name='homehero',
            old_name='heading',
            new_name='heading_line1',
        ),
        migrations.RenameField(
            model_name='homehero',
            old_name='hero_image_public_id',
            new_name='phone_image_public_id',
        ),
        migrations.RenameField(
            model_name='homehero',
            old_name='hero_image_url',
            new_name='phone_image_url',
        ),
        migrations.AddField(
            model_name='homehero',
            name='heading_line2',
            field=models.CharField(blank=True, default='', help_text="Rendered on its own line, in the brand gradient (e.g. 'with a Single Tap').", max_length=255),
        ),
        migrations.AddField(
            model_name='homehero',
            name='nfc_card_image_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homehero',
            name='nfc_card_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='homeherofeaturehighlight',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
