# Generated by Django 6.0.1 on 2026-09-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0006_emailsettings_paymentsettings_securitysettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='story_image_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
