# Generated by Django 6.0.1 on 2026-09-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0007_aboutpage_story_image_public_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesAnalyticsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, default='', max_length=150)),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('dashboard_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('dashboard_image_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('cta_text', models.CharField(blank=True, default='', max_length=100)),
                ('cta_url', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Features Analytics Section',
                'verbose_name_plural': 'Features Analytics Section',
            },
        ),
        migrations.CreateModel(
            name='FeaturesCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('button_text', models.CharField(blank=True, default='', max_length=100)),
                ('button_url', models.CharField(blank=True, default='', max_length=255)),
                ('background_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('background_image_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Features CTA Section',
                'verbose_name_plural': 'Features CTA Section',
            },
        ),
        migrations.CreateModel(
            name='FeaturesPageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, default='', help_text='Lucide icon name', max_length=50)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('image_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('gradient', models.CharField(blank=True, default='', help_text='Optional CSS gradient', max_length=255)),
                ('cta_text', models.CharField(blank=True, default='', max_length=100)),
                ('cta_url', models.CharField(blank=True, default='', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Features Page Card',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeaturesPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, default='', max_length=200)),
                ('page_subtitle', models.TextField(blank=True, default='')),
                ('hero_badge', models.CharField(blank=True, default='', max_length=150)),
                ('hero_heading', models.CharField(blank=True, default='', max_length=255)),
                ('hero_description', models.TextField(blank=True, default='')),
                ('hero_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('hero_image_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('primary_cta_text', models.CharField(blank=True, default='', max_length=100)),
                ('primary_cta_url', models.CharField(blank=True, default='', max_length=255)),
                ('secondary_cta_text', models.CharField(blank=True, default='', max_length=100)),
                ('secondary_cta_url', models.CharField(blank=True, default='', max_length=255)),
                ('trust_badge_text', models.CharField(blank=True, default='', max_length=150)),
                ('trusted_users_count', models.CharField(blank=True, default='', help_text='e.g. 10,000+', max_length=50)),
                ('features_grid_heading', models.CharField(blank=True, default='', max_length=255)),
                ('features_grid_subtitle', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Features Page Settings',
                'verbose_name_plural': 'Features Page Settings',
            },
        ),
        migrations.CreateModel(
            name='FeaturesShowcaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, default='', max_length=150)),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('main_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('main_image_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('card_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('card_image_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Features Showcase Section',
                'verbose_name_plural': 'Features Showcase Section',
            },
        ),
        migrations.AlterField(
            model_name='statistic',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('features', 'Features')], default='home', max_length=20),
        ),
    ]
