# Generated by Django 6.0.1 on 2026-09-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0008_featuresanalyticssection_featurescta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurespagesettings',
            name='hero_heading',
        ),
        migrations.AddField(
            model_name='featurespagesettings',
            name='hero_heading_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='featurespagesettings',
            name='hero_heading_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
