# Generated by Django 6.0.1 on 2026-09-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0010_seed_features_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCardPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, default='', max_length=200)),
                ('page_subtitle', models.TextField(blank=True, default='')),
                ('theme_section_heading', models.CharField(blank=True, default='', max_length=200)),
                ('theme_section_subtitle', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Card Page Settings',
                'verbose_name_plural': 'Order Card Page Settings',
            },
        ),
        migrations.CreateModel(
            name='OrderCardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('design', models.CharField(blank=True, default='', max_length=255)),
                ('best_for', models.CharField(blank=True, default='', max_length=150)),
                ('template_count', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.TextField(blank=True, default='', help_text='One feature per line')),
                ('card_type', models.CharField(choices=[('WOODEN', 'Wooden'), ('CUSTOM', 'Custom'), ('REVIEW', 'Google Review Card')], max_length=10)),
                ('card_tone', models.CharField(blank=True, choices=[('front', 'Front (brand gradient)'), ('back', 'Back'), ('gold', 'Gold'), ('custom', 'Custom (multi-hue)')], default='', max_length=10)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('image_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('image_caption', models.CharField(blank=True, default='', max_length=255)),
                ('color_name', models.CharField(blank=True, default='', max_length=50)),
                ('color_hex', models.CharField(blank=True, default='', max_length=7)),
                ('theme_plan_copy', models.TextField(blank=True, default='')),
                ('popular', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Order Card Product',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderCardTrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Order Card Trust Badge',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
