# Generated by Django 6.0.1 on 2026-09-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_content', '0012_seed_order_card_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTemplatePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(choices=[('classic', 'classic'), ('signature', 'signature'), ('creative', 'creative'), ('executive', 'executive'), ('luxury', 'luxury'), ('future', 'future'), ('nature', 'nature'), ('glass', 'glass'), ('impact', 'impact')], max_length=30, unique=True)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('image_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile Template Preview',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
