# Generated by Django 6.0.1 on 2026-09-17 09:54

from django.db import migrations, models


def seed_office_address(apps, schema_editor):
    """Backfills the fields that were previously a hardcoded frontend
    constant (lib/order-tracking.ts's SHIPPING_ORIGIN: name/city/state)
    so every "From" display keeps showing the same real values it already
    did, the moment this migration runs — Admin can then edit them freely
    from Settings > General. Only backfills the row that was actually
    hardcoded before; every other new field is left blank for Admin to
    fill in, never invented."""
    GeneralSettings = apps.get_model("website_content", "GeneralSettings")
    GeneralSettings.objects.filter(office_name="").update(
        office_name="VR's NEXORA",
        office_city="Hyderabad",
        office_state="Telangana",
        office_country="India",
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("website_content", "0014_seed_profile_template_previews"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="office_address_line1",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="office_address_line2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="office_city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="office_country",
            field=models.CharField(blank=True, default="India", max_length=100),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="office_district",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="office_landmark",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="office_locality",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="office_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="office_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="office_pincode",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="office_state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RunPython(seed_office_address, noop_reverse),
    ]
