# Generated by Django 6.1.1 on 2026-09-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_content", "0015_generalsettings_office_address_line1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeOurStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "image_public_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Home Our Story",
                "verbose_name_plural": "Home Our Story",
            },
        ),
        migrations.AddField(
            model_name="homehowitfeels",
            name="image_public_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="homehowitfeels",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
