# Generated by Django 6.1.1 on 2026-09-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website_content",
            "0016_homeourstory_homehowitfeels_image_public_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="company_logo_public_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="company_logo_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="favicon_public_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="favicon_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="support_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="support_phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="website_url",
            field=models.URLField(blank=True, default="", max_length=255),
        ),
    ]
