# Generated by Django 6.1.1 on 2026-09-07 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nfc_cards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TapEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("TAP", "Card Tapped"),
                            ("QR_SCAN", "QR Code Scanned"),
                            ("PROFILE_VIEW", "Profile Viewed"),
                            ("CONTACT_SAVED", "Contact Saved"),
                            ("SHARED", "Shared"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        choices=[
                            ("ANDROID", "Android"),
                            ("IOS", "iOS"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("visitor_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tap_events",
                        to="nfc_cards.nfccard",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tap_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
