# Generated by Django 6.0.1 on 2026-09-07 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PROFILE_VIEW', 'Profile View'), ('NFC_TAP', 'NFC Tap'), ('QR_SCAN', 'QR Scan'), ('SOCIAL_CLICK', 'Social Link Click')], db_index=True, max_length=20)),
                ('device', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('metadata', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type', 'created_at'], name='customer_an_user_id_619118_idx')],
            },
        ),
    ]
