from django.urls import path

from website_content.views.admin import (
    AboutBuiltFromExperienceAdminView,
    AboutBuiltFromExperienceImageAdminView,
    AboutFeatureHighlightAdminDetailView,
    AboutFeatureHighlightAdminListView,
    AboutFeatureHighlightAdminReorderView,
    AboutMissionAdminView,
    AboutPageAdminView,
    AboutWhyChooseAdminDetailView,
    AboutWhyChooseAdminListView,
    AboutWhyChooseAdminReorderView,
    CompanyAdminDetailView,
    CompanyAdminListView,
    CompanyAdminReorderView,
    CompanyImageAdminView,
    ContactMessageAdminDetailView,
    ContactMessageAdminListView,
    ContactMessageReplyAdminView,
    FaqAdminDetailView,
    FaqAdminListView,
    FaqAdminReorderView,
    FeatureAdminDetailView,
    FeatureAdminListView,
    FeatureAdminReorderView,
    GeneralSettingsAdminView,
    HomeCTAAdminView,
    HomeHeroAdminView,
    HomeHeroFeatureHighlightAdminDetailView,
    HomeHeroFeatureHighlightAdminListView,
    HomeHeroFeatureHighlightAdminReorderView,
    HomeHeroImageAdminView,
    HomeHowItFeelsAdminView,
    HomeHowItFeelsPointAdminDetailView,
    HomeHowItFeelsPointAdminListView,
    HomeHowItFeelsPointAdminReorderView,
    HowItWorksStepAdminDetailView,
    HowItWorksStepAdminListView,
    HowItWorksStepAdminReorderView,
    StatisticAdminDetailView,
    StatisticAdminListView,
    StatisticAdminReorderView,
    TestimonialAdminDetailView,
    TestimonialAdminListView,
    TestimonialAdminReorderView,
    TestimonialImageAdminView,
    ValueAdminDetailView,
    ValueAdminListView,
    ValueAdminReorderView,
)

urlpatterns = [
    # Home
    path("home/hero/", HomeHeroAdminView.as_view(), name="admin-home-hero"),
    path("home/hero/image/", HomeHeroImageAdminView.as_view(), name="admin-home-hero-image"),
    path(
        "home/hero-features/",
        HomeHeroFeatureHighlightAdminListView.as_view(),
        name="admin-home-hero-features",
    ),
    path(
        "home/hero-features/reorder/",
        HomeHeroFeatureHighlightAdminReorderView.as_view(),
        name="admin-home-hero-features-reorder",
    ),
    path(
        "home/hero-features/<int:pk>/",
        HomeHeroFeatureHighlightAdminDetailView.as_view(),
        name="admin-home-hero-feature-detail",
    ),
    path("home/how-it-feels/", HomeHowItFeelsAdminView.as_view(), name="admin-home-how-it-feels"),
    path(
        "home/how-it-feels-points/",
        HomeHowItFeelsPointAdminListView.as_view(),
        name="admin-home-how-it-feels-points",
    ),
    path(
        "home/how-it-feels-points/reorder/",
        HomeHowItFeelsPointAdminReorderView.as_view(),
        name="admin-home-how-it-feels-points-reorder",
    ),
    path(
        "home/how-it-feels-points/<int:pk>/",
        HomeHowItFeelsPointAdminDetailView.as_view(),
        name="admin-home-how-it-feels-point-detail",
    ),
    path("home/cta/", HomeCTAAdminView.as_view(), name="admin-home-cta"),
    # About
    path("about/page/", AboutPageAdminView.as_view(), name="admin-about-page"),
    path(
        "about/features/",
        AboutFeatureHighlightAdminListView.as_view(),
        name="admin-about-features",
    ),
    path(
        "about/features/reorder/",
        AboutFeatureHighlightAdminReorderView.as_view(),
        name="admin-about-features-reorder",
    ),
    path(
        "about/features/<int:pk>/",
        AboutFeatureHighlightAdminDetailView.as_view(),
        name="admin-about-feature-detail",
    ),
    path("about/mission/", AboutMissionAdminView.as_view(), name="admin-about-mission"),
    path(
        "about/why-choose/",
        AboutWhyChooseAdminListView.as_view(),
        name="admin-about-why-choose",
    ),
    path(
        "about/why-choose/reorder/",
        AboutWhyChooseAdminReorderView.as_view(),
        name="admin-about-why-choose-reorder",
    ),
    path(
        "about/why-choose/<int:pk>/",
        AboutWhyChooseAdminDetailView.as_view(),
        name="admin-about-why-choose-detail",
    ),
    path(
        "about/built-from-experience/",
        AboutBuiltFromExperienceAdminView.as_view(),
        name="admin-about-built-from-experience",
    ),
    path(
        "about/built-from-experience/image/",
        AboutBuiltFromExperienceImageAdminView.as_view(),
        name="admin-about-built-from-experience-image",
    ),
    # Shared
    path("values/", ValueAdminListView.as_view(), name="admin-values"),
    path("values/reorder/", ValueAdminReorderView.as_view(), name="admin-values-reorder"),
    path("values/<int:pk>/", ValueAdminDetailView.as_view(), name="admin-value-detail"),
    path("features/", FeatureAdminListView.as_view(), name="admin-features"),
    path("features/reorder/", FeatureAdminReorderView.as_view(), name="admin-features-reorder"),
    path("features/<int:pk>/", FeatureAdminDetailView.as_view(), name="admin-feature-detail"),
    path("how-it-works/", HowItWorksStepAdminListView.as_view(), name="admin-how-it-works"),
    path(
        "how-it-works/reorder/",
        HowItWorksStepAdminReorderView.as_view(),
        name="admin-how-it-works-reorder",
    ),
    path(
        "how-it-works/<int:pk>/",
        HowItWorksStepAdminDetailView.as_view(),
        name="admin-how-it-works-detail",
    ),
    path("faqs/", FaqAdminListView.as_view(), name="admin-faqs"),
    path("faqs/reorder/", FaqAdminReorderView.as_view(), name="admin-faqs-reorder"),
    path("faqs/<int:pk>/", FaqAdminDetailView.as_view(), name="admin-faq-detail"),
    path("testimonials/", TestimonialAdminListView.as_view(), name="admin-testimonials"),
    path(
        "testimonials/reorder/",
        TestimonialAdminReorderView.as_view(),
        name="admin-testimonials-reorder",
    ),
    path(
        "testimonials/<int:pk>/",
        TestimonialAdminDetailView.as_view(),
        name="admin-testimonial-detail",
    ),
    path(
        "testimonials/<int:pk>/image/",
        TestimonialImageAdminView.as_view(),
        name="admin-testimonial-image",
    ),
    path("companies/", CompanyAdminListView.as_view(), name="admin-companies"),
    path("companies/reorder/", CompanyAdminReorderView.as_view(), name="admin-companies-reorder"),
    path("companies/<int:pk>/", CompanyAdminDetailView.as_view(), name="admin-company-detail"),
    path(
        "companies/<int:pk>/image/",
        CompanyImageAdminView.as_view(),
        name="admin-company-image",
    ),
    path("statistics/", StatisticAdminListView.as_view(), name="admin-statistics"),
    path(
        "statistics/reorder/",
        StatisticAdminReorderView.as_view(),
        name="admin-statistics-reorder",
    ),
    path("statistics/<int:pk>/", StatisticAdminDetailView.as_view(), name="admin-statistic-detail"),
    # Contact messages
    path("contact-messages/", ContactMessageAdminListView.as_view(), name="admin-contact-messages"),
    path(
        "contact-messages/<int:pk>/",
        ContactMessageAdminDetailView.as_view(),
        name="admin-contact-message-detail",
    ),
    path(
        "contact-messages/<int:pk>/reply/",
        ContactMessageReplyAdminView.as_view(),
        name="admin-contact-message-reply",
    ),
    # Settings
    path("settings/", GeneralSettingsAdminView.as_view(), name="admin-settings"),
]
