# Generated by Django 6.0.1 on 2026-09-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailotp",
            name="code",
        ),
        migrations.AddField(
            model_name="emailotp",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="channel",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("SMS", "SMS")],
                default="EMAIL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="code_hash",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailotp",
            name="reset_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="reset_token_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
