# Generated by Django 6.0.1 on 2026-09-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_emailotp_code_emailotp_attempts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailotp",
            name="channel",
        ),
    ]
