# Generated by Django 6.0.1 on 2026-09-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_google_avatar_url_user_google_id'),
        ('accounts', '0003_remove_emailotp_channel'),
    ]

    operations = [
    ]
