# Generated by Django 6.0.1 on 2026-09-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='card_type',
            field=models.CharField(choices=[('CLASSIC', 'Classic'), ('PREMIUM', 'Premium'), ('WOODEN', 'Wooden'), ('CUSTOM', 'Custom')], max_length=10),
        ),
    ]
