# Generated by Django 6.0.1 on 2026-09-07 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_email', models.BooleanField(default=True)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_company', models.BooleanField(default=True)),
                ('show_social_links', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('te', 'Telugu')], default='en', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('notify_order_updates', models.BooleanField(default=True)),
                ('notify_nfc_updates', models.BooleanField(default=True)),
                ('notify_profile_views', models.BooleanField(default=False)),
                ('notify_system_messages', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
