import { useEffect, useState, type FormEvent } from "react"
import { useNavigate } from "react-router-dom"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { toast } from "sonner"
import { CheckCircle2, Info, MapPin, Plus } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Skeleton } from "@/components/ui/skeleton"
import { AddressFormDialog } from "@/components/customer/AddressFormDialog"
import { useCart } from "@/hooks/useCart"
import { sanitizeCartLines } from "@/store/cart-store"
import { useCustomerAuthStore } from "@/store/auth-store"
import { ordersApi, customerAddressApi, ApiError, type CreateOrderPayload } from "@/lib/api"
import { formatCurrency } from "@/lib/mock-api"
import { usePublicSettings } from "@/hooks/usePublicSettings"
import { cn } from "@/lib/utils"
import type { CustomerAddress } from "@/types"

// The customer's delivery address now always comes from their saved
// address book (customerAddressApi — see components/customer/
// AddressFormDialog.tsx) rather than being typed fresh on every order.
// Placing an order sends `address_id`; the backend copies that address's
// fields into the order's own shipping_* snapshot columns exactly once
// (see orders/services.py's compose_shipping_snapshot) — editing or
// deleting the saved address afterward never changes a past order.
function AddressOption({
  address,
  selected,
  onSelect,
}: {
  address: CustomerAddress
  selected: boolean
  onSelect: () => void
}) {
  return (
    <button
      type="button"
      onClick={onSelect}
      className={cn(
        "flex w-full flex-col items-start gap-1 rounded-xl border p-4 text-left text-sm transition-colors",
        selected ? "border-primary bg-primary/5" : "border-border hover:bg-muted/40",
      )}
    >
      <span className="flex w-full items-center justify-between gap-2">
        <span className="font-semibold text-foreground">{address.label || "Address"}</span>
        {address.isDefault && <span className="text-xs font-medium text-primary">DEFAULT</span>}
      </span>
      <span className="text-foreground">{address.fullName}</span>
      <span className="text-muted-foreground">
        {[address.addressLine1, address.locality].filter(Boolean).join(", ")}
      </span>
      <span className="text-muted-foreground">
        {[address.city, address.state].filter(Boolean).join(", ")} - {address.pincode}
      </span>
    </button>
  )
}

export default function Checkout() {
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const customer = useCustomerAuthStore((s) => s.customer)
  const { lines, subtotal, couponCode, discount, clearCart } = useCart()
  const { settings } = usePublicSettings()

  const [selectedAddressId, setSelectedAddressId] = useState<string | null>(null)
  const [selectorOpen, setSelectorOpen] = useState(false)
  const [formOpen, setFormOpen] = useState(false)

  // One id per checkout attempt (this page mount) — sent on every submit so
  // a double-click or retry resends the *same* id, letting the backend
  // recognize the resend and return the original order instead of creating
  // a second one (see orders/views.py CustomerOrderListCreateView.post). A
  // fresh id is only generated by mounting this page again (e.g. after a
  // successful order navigates away and the user starts a new one).
  const [idempotencyKey] = useState(() => crypto.randomUUID())

  const addressesQuery = useQuery({
    queryKey: ["customer-addresses"],
    queryFn: customerAddressApi.list,
    enabled: Boolean(customer),
  })
  const addresses = addressesQuery.data ?? []

  // Auto-select the default address the first time addresses load (or the
  // first one if none is flagged default) — the customer can still pick a
  // different saved address before placing the order.
  useEffect(() => {
    if (selectedAddressId) return
    if (addresses.length === 0) return
    const preferred = addresses.find((a) => a.isDefault) ?? addresses[0]
    setSelectedAddressId(preferred.id)
  }, [addresses, selectedAddressId])

  const selectedAddress = addresses.find((a) => a.id === selectedAddressId) ?? null

  const sub = subtotal()
  // The live Order backend doesn't model a separate shipping charge yet —
  // the total shown here must match exactly what gets recorded server-side
  // (subtotal minus discount), so no shipping fee is added on top.
  const total = Math.max(0, sub - discount)

  const placeOrderMutation = useMutation({
    mutationFn: (payload: CreateOrderPayload) => ordersApi.create(payload),
    onSuccess: (order) => {
      clearCart()
      navigate("/order-success", {
        state: { orderId: String(order.id), trackingToken: order.tracking_token, customerName: customer?.name },
      })
    },
    onError: (err) => {
      const message = err instanceof ApiError ? err.message : "Something went wrong placing your order."
      toast.error(message)
    },
  })

  if (!customer) {
    return null
  }

  function handleAddressSaved(address: CustomerAddress) {
    queryClient.invalidateQueries({ queryKey: ["customer-addresses"] })
    setSelectedAddressId(address.id)
    setSelectorOpen(false)
  }

  function handleSubmit(e: FormEvent) {
    e.preventDefault()
    if (placeOrderMutation.isPending) return
    if (lines.length === 0) {
      toast.error("Your cart is empty.")
      return
    }
    if (!selectedAddress) {
      toast.error("Please select or add a delivery address.")
      return
    }

    // Belt-and-braces alongside the cart store's own rehydration-time
    // filter (cart-store.ts) — same VALID_CARD_TYPES check, not a second
    // definition of it — so a retired card type can never reach the order
    // API from this call site either, even in the same session.
    const validLines = sanitizeCartLines(lines)
    if (validLines.length === 0) {
      toast.error("Your cart no longer contains any available products. Please add an item to continue.")
      return
    }

    placeOrderMutation.mutate({
      idempotency_key: idempotencyKey,
      items: validLines.map((l) => ({
        product_id: l.productId,
        name: l.name,
        card_type: l.cardType.toUpperCase(),
        color: l.color.name,
        qty: l.qty,
        price: l.price,
      })),
      shipping: 0,
      // No payment gateway is wired up yet (see the note below the billing
      // form) — orders are placed as Cash on Delivery / pay-on-confirmation
      // until one exists, so there's nothing for the customer to pick here.
      payment_method: "COD",
      address_id: Number(selectedAddress.id),
    })
  }

  return (
    <div className="mx-auto max-w-6xl px-4 py-12">
      <h1 className="text-3xl font-bold tracking-tight text-foreground">Checkout</h1>

      <form onSubmit={handleSubmit} className="mt-8 grid gap-8 lg:grid-cols-3">
        <div className="space-y-6 lg:col-span-2">
          <div className="rounded-2xl border bg-card p-6 shadow-sm">
            <div className="flex items-center justify-between gap-2">
              <h2 className="flex items-center gap-2 text-lg font-semibold text-foreground">
                <MapPin className="size-4 text-primary" /> Delivery Address
              </h2>
              {addresses.length > 0 && (
                <Button type="button" variant="outline" size="sm" onClick={() => setSelectorOpen((v) => !v)}>
                  {selectorOpen ? "Close" : "Change Address"}
                </Button>
              )}
            </div>

            {addressesQuery.isLoading ? (
              <div className="mt-4 space-y-2">
                <Skeleton className="h-24 w-full rounded-xl" />
              </div>
            ) : addressesQuery.isError ? (
              <div className="mt-4 flex flex-col items-center gap-2 py-6 text-center">
                <p className="text-sm text-muted-foreground">Unable to load your saved addresses.</p>
                <Button variant="outline" size="sm" onClick={() => addressesQuery.refetch()}>
                  Retry
                </Button>
              </div>
            ) : addresses.length === 0 ? (
              <div className="mt-4 flex flex-col items-center gap-3 rounded-xl border border-dashed p-8 text-center">
                <p className="text-sm font-medium text-foreground">No delivery address found.</p>
                <Button type="button" onClick={() => setFormOpen(true)}>
                  <Plus className="size-4" /> Add Delivery Address
                </Button>
              </div>
            ) : selectorOpen ? (
              <div className="mt-4 flex flex-col gap-2">
                {addresses.map((address) => (
                  <AddressOption
                    key={address.id}
                    address={address}
                    selected={address.id === selectedAddressId}
                    onSelect={() => {
                      setSelectedAddressId(address.id)
                      setSelectorOpen(false)
                    }}
                  />
                ))}
                <Button type="button" variant="outline" className="mt-1" onClick={() => setFormOpen(true)}>
                  <Plus className="size-4" /> Add New Address
                </Button>
              </div>
            ) : selectedAddress ? (
              <div className="mt-4 space-y-0.5 text-sm text-muted-foreground">
                <p className="font-semibold text-foreground">
                  {selectedAddress.label || "Address"}
                  {selectedAddress.isDefault && (
                    <span className="ml-2 text-xs font-medium text-primary">DEFAULT</span>
                  )}
                </p>
                <p className="font-medium text-foreground">{selectedAddress.fullName}</p>
                <p>{selectedAddress.addressLine1}</p>
                {selectedAddress.addressLine2 && <p>{selectedAddress.addressLine2}</p>}
                {selectedAddress.landmark && <p>Near {selectedAddress.landmark}</p>}
                <p>{[selectedAddress.locality, selectedAddress.city].filter(Boolean).join(", ")}</p>
                <p>{selectedAddress.district} District</p>
                <p>
                  {selectedAddress.state} - {selectedAddress.pincode}
                </p>
                <p>{selectedAddress.country}</p>
                <p className="pt-2 flex items-center gap-1.5 text-success">
                  <CheckCircle2 className="size-3.5" /> Address details verified
                </p>
              </div>
            ) : null}
          </div>

          <div className="flex items-start gap-2 rounded-2xl border bg-muted/30 p-4 text-sm text-muted-foreground">
            <Info className="mt-0.5 size-4 shrink-0" />
            <p>
              Online payment isn&apos;t available yet — placing an order reserves your card and our team will
              contact you to confirm payment and shipping.
            </p>
          </div>
        </div>

        <div className="h-fit rounded-2xl border bg-card p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-foreground">Order Summary</h2>
          <div className="mt-4 space-y-2 border-b pb-4 text-sm">
            {lines.map((l) => (
              <div key={l.lineId} className="flex justify-between text-muted-foreground">
                <span>
                  {l.name} × {l.qty}
                </span>
                <span className="text-foreground">{formatCurrency(l.price * l.qty, settings.currency)}</span>
              </div>
            ))}
          </div>
          <div className="mt-4 space-y-2 text-sm">
            <div className="flex justify-between text-muted-foreground">
              <span>Subtotal</span>
              <span className="text-foreground">{formatCurrency(sub, settings.currency)}</span>
            </div>
            {couponCode && (
              <div className="flex justify-between text-success">
                <span>Discount ({couponCode})</span>
                <span>- {formatCurrency(discount, settings.currency)}</span>
              </div>
            )}
            <div className="flex justify-between border-t pt-3 text-base font-semibold text-foreground">
              <span>Total</span>
              <span>{formatCurrency(total, settings.currency)}</span>
            </div>
          </div>
          <Button
            type="submit"
            size="lg"
            className="mt-6 w-full"
            disabled={!selectedAddress || placeOrderMutation.isPending}
          >
            {placeOrderMutation.isPending ? "Placing Order…" : "Place Order"}
          </Button>
        </div>
      </form>

      <AddressFormDialog open={formOpen} onOpenChange={setFormOpen} onSaved={handleAddressSaved} />
    </div>
  )
}
