# Generated by Django 6.1.1 on 2026-09-04 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NfcCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "serial_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("PREMIUM", "Premium"),
                            ("WOODEN", "Wooden"),
                            ("METAL", "Metal"),
                        ],
                        default="STANDARD",
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(default="Black", max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ASSIGNED", "Assigned"),
                            ("INACTIVE", "Inactive"),
                            ("BLOCKED", "Blocked"),
                            ("LOST", "Lost"),
                            ("UNASSIGNED", "Unassigned"),
                        ],
                        default="UNASSIGNED",
                        max_length=10,
                    ),
                ),
                ("assigned_on", models.DateTimeField(blank=True, null=True)),
                ("activated_on", models.DateTimeField(blank=True, null=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfc_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
