# Generated by Django 6.0.1 on 2026-09-10 06:14

from django.db import migrations, models


def rename_standard_to_classic(apps, schema_editor):
    NfcCard = apps.get_model("nfc_cards", "NfcCard")
    NfcCard.objects.filter(card_type="STANDARD").update(card_type="CLASSIC")


def rename_classic_to_standard(apps, schema_editor):
    NfcCard = apps.get_model("nfc_cards", "NfcCard")
    NfcCard.objects.filter(card_type="CLASSIC").update(card_type="STANDARD")


class Migration(migrations.Migration):

    dependencies = [
        ("nfc_cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfccard",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("CLASSIC", "Classic"),
                    ("PREMIUM", "Premium"),
                    ("WOODEN", "Wooden"),
                    ("METAL", "Metal"),
                ],
                default="CLASSIC",
                max_length=10,
            ),
        ),
        # Existing rows still literally say "STANDARD" (the enum's old value) —
        # rewrite them so stored data matches the renamed choice.
        migrations.RunPython(rename_standard_to_classic, rename_classic_to_standard),
    ]
