# Generated by Django 6.0.1 on 2026-09-10 06:29

from django.db import migrations, models


def rename_metal_to_custom(apps, schema_editor):
    NfcCard = apps.get_model("nfc_cards", "NfcCard")
    NfcCard.objects.filter(card_type="METAL").update(card_type="CUSTOM")


def rename_custom_to_metal(apps, schema_editor):
    NfcCard = apps.get_model("nfc_cards", "NfcCard")
    NfcCard.objects.filter(card_type="CUSTOM").update(card_type="METAL")


class Migration(migrations.Migration):

    dependencies = [
        ("nfc_cards", "0002_alter_nfccard_card_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfccard",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("CLASSIC", "Classic"),
                    ("PREMIUM", "Premium"),
                    ("WOODEN", "Wooden"),
                    ("CUSTOM", "Custom"),
                ],
                default="CLASSIC",
                max_length=10,
            ),
        ),
        # Existing rows still literally say "METAL" (the enum's old value) —
        # rewrite them so stored data matches the renamed choice.
        migrations.RunPython(rename_metal_to_custom, rename_custom_to_metal),
    ]
