# Generated by Django 6.1.1 on 2026-09-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfc_cards", "0003_alter_nfccard_card_type"),
    ]

    operations = [
        # Only the Python-level default changes (CLASSIC -> CUSTOM), since
        # Classic/Premium are retired from new sale — new cards created
        # without an explicit card_type should land on the one remaining
        # sellable tier, not a retired one. Choices are unchanged and no
        # existing rows are rewritten; this affects only future creates.
        migrations.AlterField(
            model_name="nfccard",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("CLASSIC", "Classic"),
                    ("PREMIUM", "Premium"),
                    ("WOODEN", "Wooden"),
                    ("CUSTOM", "Custom"),
                ],
                default="CUSTOM",
                max_length=10,
            ),
        ),
    ]
