# Generated by Django 6.0.1 on 2026-09-10 06:14

from django.db import migrations


def rename_standard_to_classic(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    OrderItem.objects.filter(card_type="STANDARD").update(card_type="CLASSIC")


def rename_classic_to_standard(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    OrderItem.objects.filter(card_type="CLASSIC").update(card_type="STANDARD")


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_idempotency_key_and_more"),
    ]

    # OrderItem.card_type is a plain CharField (no `choices`, validated only
    # at the serializer layer against NfcCard.CardType) — no schema change is
    # needed here, only rewriting existing rows so historical order items
    # match the renamed CLASSIC value nfc_cards.NfcCard now uses.
    operations = [
        migrations.RunPython(rename_standard_to_classic, rename_classic_to_standard),
    ]
