# Generated by Django 6.0.1 on 2026-09-10 06:29

from django.db import migrations


def rename_metal_to_custom(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    OrderItem.objects.filter(card_type="METAL").update(card_type="CUSTOM")


def rename_custom_to_metal(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    OrderItem.objects.filter(card_type="CUSTOM").update(card_type="METAL")


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_standard_card_type_to_classic"),
    ]

    operations = [
        migrations.RunPython(rename_metal_to_custom, rename_custom_to_metal),
    ]
