# Generated by Django 6.0.5 on 2026-09-17 07:45, split into a safe
# add-nullable / backfill-unique-values / enforce-not-null-and-unique
# sequence (see 0007/0008) — a plain AddField with unique=True and a
# uuid.uuid4 default fails on SQLite's table-rebuild strategy, which
# evaluates the default once and reuses it for every existing row instead
# of calling it per row.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_delete_retired_card_type_order_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_token",
            field=models.UUIDField(null=True, editable=False, db_index=True),
        ),
    ]
