# Generated by Django 6.0.1 on 2026-09-17 09:37

import random
import string

from django.db import migrations, models


def backfill_order_numbers(apps, schema_editor):
    """Every order created before this migration has order_number=NULL —
    give each one a real code so it's immediately trackable on the public
    /track-order page, same format generate_order_number() in
    orders/models.py produces for new orders going forward."""
    Order = apps.get_model("orders", "Order")
    existing = set(Order.objects.exclude(order_number__isnull=True).values_list("order_number", flat=True))
    for order in Order.objects.filter(order_number__isnull=True).order_by("id"):
        while True:
            candidate = "NXTRK" + "".join(random.choices(string.digits, k=6))
            if candidate not in existing:
                existing.add(candidate)
                break
        order.order_number = candidate
        order.save(update_fields=["order_number"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_delete_retired_card_type_order_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, unique=True
            ),
        ),
        migrations.RunPython(backfill_order_numbers, noop_reverse),
    ]
