# Generated by Django 6.0.1 on 2026-09-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_number"),
        ("orders", "0008_alter_order_tracking_token"),
    ]

    operations = []
